import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Press_Start_2P, Orbitron, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const pressStart = Press_Start_2P({
  subsets: ["latin"],
  weight: "400",
});

export const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {

  title: "Electo - Your One-Stop Shop for Electronics",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", // ✅ Add favicon here
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} antialiased`}
      >
        <div className="w-full bg-blue-50 min-h-screen flex flex-col">
          <div className="mx-auto w-full max-w-5xl px-4 sm:px-6 lg:px-8 flex-1 mt-6">
            <Navbar />
            {children}
            <Footer />
          </div>
        </div>

        {/* <div className="w-full bg-blue-50 min-h-screen flex flex-col">
  <div className="mx-auto w-full max-w-5xl px-4 sm:px-6 lg:px-8 flex-1">
    <Navbar />
    <main className="py-8">{children}</main>
    <Footer />
  </div>
</div>
 */}

      </body>
    </html>
  );
}
